# lextab.py. This file automatically created by PLY (version 3.10). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('RPAREN', 'ARROW', 'PLUS', 'FI', 'LTEQ', 'ESAC', 'DIVIDE', 'CASE', 'LT', 'RBRACE', 'INT_COMP', 'LET', 'OF', 'ID', 'COMMA', 'ASSIGN', 'POOL', 'COLON', 'DOT', 'SELF', 'LPAREN', 'NEW', 'IF', 'ISVOID', 'TYPE', 'LBRACE', 'STRING', 'THEN', 'AT', 'NOT', 'CLASS', 'MULTIPLY', 'SEMICOLON', 'LOOP', 'IN', 'WHILE', 'INTEGER', 'ELSE', 'MINUS', 'EQ', 'INHERITS', 'BOOLEAN'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive', 'STRING': 'exclusive', 'COMMENT': 'exclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_BOOLEAN>(true|false))|(?P<t_INTEGER>\\d+)|(?P<t_TYPE>[A-Z][a-zA-Z_0-9]*)|(?P<t_ID>[a-z_][a-zA-Z_0-9]*)|(?P<t_newline>\\n+)|(?P<t_start_string>\\")|(?P<t_start_comment>\\(\\*)|(?P<t_ignore_SINGLE_LINE_COMMENT>\\-\\-[^\\n]*)|(?P<t_LTEQ>\\<\\=)|(?P<t_ARROW>\\=\\>)|(?P<t_ASSIGN>\\<\\-)|(?P<t_NOT>not)|(?P<t_COMMA>\\,)|(?P<t_RBRACE>\\})|(?P<t_MULTIPLY>\\*)|(?P<t_COLON>\\:)|(?P<t_LPAREN>\\()|(?P<t_DOT>\\.)|(?P<t_MINUS>\\-)|(?P<t_EQ>\\=)|(?P<t_SEMICOLON>\\;)|(?P<t_AT>\\@)|(?P<t_LBRACE>\\{)|(?P<t_LT>\\<)|(?P<t_PLUS>\\+)|(?P<t_RPAREN>\\))|(?P<t_DIVIDE>\\/)|(?P<t_INT_COMP>~)', [None, ('t_BOOLEAN', 'BOOLEAN'), None, ('t_INTEGER', 'INTEGER'), ('t_TYPE', 'TYPE'), ('t_ID', 'ID'), ('t_newline', 'newline'), ('t_start_string', 'start_string'), ('t_start_comment', 'start_comment'), (None, None), (None, 'LTEQ'), (None, 'ARROW'), (None, 'ASSIGN'), (None, 'NOT'), (None, 'COMMA'), (None, 'RBRACE'), (None, 'MULTIPLY'), (None, 'COLON'), (None, 'LPAREN'), (None, 'DOT'), (None, 'MINUS'), (None, 'EQ'), (None, 'SEMICOLON'), (None, 'AT'), (None, 'LBRACE'), (None, 'LT'), (None, 'PLUS'), (None, 'RPAREN'), (None, 'DIVIDE'), (None, 'INT_COMP')])], 'STRING': [('(?P<t_STRING_newline>\\n)|(?P<t_STRING_end>\\")|(?P<t_STRING_anything>[^\\n])', [None, ('t_STRING_newline', 'newline'), ('t_STRING_end', 'end'), ('t_STRING_anything', 'anything')])], 'COMMENT': [('(?P<t_COMMENT_startanother>\\(\\*)|(?P<t_COMMENT_end>\\*\\))', [None, ('t_COMMENT_startanother', 'startanother'), ('t_COMMENT_end', 'end')])]}
_lexstateignore = {'INITIAL': ' \t\r\x0c', 'STRING': '', 'COMMENT': ''}
_lexstateerrorf = {'INITIAL': 't_error', 'STRING': 't_STRING_error', 'COMMENT': 't_COMMENT_error'}
_lexstateeoff = {}
